language: java
dist: bionic
sudo: false
addons:
  apt:
    packages:
      - ant
      - ant-optional

jdk:
  - openjdk17
  - oraclejdk17
 
script:
  - "ant -buildfile build.xml clean check jar unittest"

notifications:
    webhooks: https://www.travisbuddy.com/
